### PR TITLE
.NET 4.0 Support

### PR DESCRIPTION
**Pull request by Misiu**
Support for .NET 4.0 using `Microsoft.Bcl.Async`

### CODE REVIEW

**Comment by damdo** [comment]
Hey @Misiu thank you very much for the contribution, we will try to take a look soon 👍

**Comment by Misiu** [comment]
@damdo could you take a look at Travis? The Job log says something about the application key, but I don't want to put my keys into code that is publicly available.

**Comment by Misiu** [comment]
@damdo any updates?

**Comment by Misiu** [comment]
ping

**Review by devdreamsolution — APPROVED** [review]

**Comment by elverkilde** [comment]
closed in favour of #104

**Pull request closed without merging**
