### PR TITLE
Reset backoff to 0 on success (was never reset), and reset connection…

### PR DESCRIPTION
**Pull request by rh78**
… and disconnection tasks upon error to make reconnect logic work

### CODE REVIEW

**Comment by rh78** [comment]
This PR fixes several issues:
1) the backoff timeout was only growing, was never reset
2) When a disconnect occured, only once a reconnect was tried, and then no reconnect attempt happened anymore, because the connection task was not set to NULL
3) The HTTP authorizer makes not much sense without any authorization means to the application server - it now supports a bearer token

**Comment by rh78** [comment]
(suggestion: it would maybe make sense to fix the HTTP authorizer in a more flexible way - e.g. like in the Java client, were the implementor could just set any headers on the request as required)

**Comment by damdo** [comment]
Hey Reinhard @rh78 thank you for your contribution, this is great!
We are taking a slightly different approach with the reconnection fix (here: https://github.com/pusher/pusher-websocket-dotnet/pull/95) but your suggestion has been really valuable. The backoff fix is 👌 and it would be nice to get it merged soon! As for the bear HTTP Auth authorization means we could discuss it on a dedicated PR.

So what we could do is, to keep this PR for the backoff fix, and open a new one for the HTTP authorization. How do you feel about it?

**Review by devdreamsolution — APPROVED** [review]

**Comment by rh78** [comment]
Could you please check if this issue is still an issue? Maybe we can close it.

**Comment by elverkilde** [comment]
This was incorporated in #112 and released as version `2.1.0`

**Pull request closed without merging**
